<?php

/**
 * Implements hook_theme().
 */
function bricks_bootstrap_theme($existing, $type, $theme, $path) {
  return [
    'eck_entity__brick__accordion' => [
      'base hook' => 'eck_entity',
    ],
    'eck_entity__brick__carousel' => [
      'base hook' => 'eck_entity',
    ],
    'eck_entity__brick__columns' => [
      'base hook' => 'eck_entity',
    ],
    'eck_entity__brick__tabs' => [
      'base hook' => 'eck_entity',
    ],
  ];
}
